### ISSUE TITLE
Crash no id

### ISSUE THREAD

**Issue by sevagh** [sevagh/surge#16]
```shell
sevagh:~ $
sevagh:~ $ surge
surge ♫
surge ♫
surge ♫ search migos
thread 'main' panicked at 'Youtube response didn't contain id', /checkout/src/libcore/option.rs:823
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Aborted (core dumped)
sevagh:~ $
sevagh:~ $
sevagh:~ $ surge
surge ♫
surge ♫
surge ♫ search lamb of god
thread 'main' panicked at 'Youtube response didn't contain id', /checkout/src/libcore/option.rs:823
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Aborted (core dumped)
sevagh:~ $
sevagh:~ $
sevagh:~ $
sevagh:~ $
```

**Comment by sevagh** [comment]
Solved with: https://github.com/sevagh/surge/commit/31b5838b3f2499f19b08fbf534d575e25a6f3dff
